#! /bin/sh
# aldc: Add LaTeX DevContainer

RELEASE=0.2.2
REPOSITORY_NAME='latex-environment'
REPOSITORY_OWNER='smkwlab'
REPOSITORY_URL="https://github.com/${REPOSITORY_OWNER}/${REPOSITORY_NAME}"
RELEASE_BASE="${REPOSITORY_NAME}-${RELEASE}"
ZIP_NAME="${RELEASE_BASE}.zip"

TARGET=${REPOSITORY_URL}/archive/refs/tags/v${RELEASE}.zip

if [ -d .devcontainer ]; then
  echo "The LaTeX environment already exists."
  exit
fi

if [ ! -d .git ]; then
  git init .
  git add .
  git rm --cached aldc
  git commit -m "initial commit"
fi

echo download LaTeX environment
curl -sLJO ${TARGET}
unzip ${ZIP_NAME}
rm ${ZIP_NAME}
cd ${RELEASE_BASE}

echo add LaTeX environment
backups=""
for i in $(find . -type f); do
    if [ -e ../${i} ]; then
        mv -f ${i} ../${i}-aldc
        backups="${backups} ${i}-aldc"
    else
        dir=../$(dirname ${i})
        if [ ! -d ${dir} ]; then
            mkdir -p ${dir}
        fi
        mv -f ${i} ../${i}
    fi
done

cd ..
rm -rf ${RELEASE_BASE}

git add .
git commit -m "add LaTeX environment"
git push

echo "The addition of the LaTeX environment has been completed."

if [ "${backups}" != "" ]; then
    echo You may delete the following files: ${backups}
fi
